### ISSUE TITLE
Rask に議事録の CRUD を移植する

### ISSUE THREAD

**Issue by nakagawa1210** [nomlab/rask#10]
Created from [AI0799](http://jay.swlab.cs.okayama-u.ac.jp/minutes/1190?ai=0799) of minute 1190.
+ Rask に議事録の CRUD を移植する -->(中川 !:0799)

**Comment by nakagawa1210** [comment]
やったこと
+ 議事録のCRUDについて一通りの機能を実装した．

まだ実装できていないこと
+ タグ機能
+ プレビュー機能
+ マークダウン変換機能

**Comment by nakagawa1210** [comment]
# やったこと
+ マークダウン変換機能の実装
+ タブの実装

# まだ実装できていないこと
+ タグ機能
+ プレビュー機能

**Comment by nakagawa1210** [comment]
### やったこと
  + preview タブの修正
      + 表示範囲を固定
      + bootstrap を使用するとCSSが衝突して表示が変わってしまっていたため，タブをCSSを用いて作成，タブ切り替えの際にマークダウンに変換する箇所をJSで書き直した．
  + バリデーションの追加
    + 文書作成時に未入力項目があるとエラーメッセージを表示
    + model にバリデーションを追加して文書保存時に未入力項目があると保存処理を行わないように修正
  + 文書表示の際に文書データに問題があっても表示できるようにする
    + 登録されている文書情報がnil であっても空白が表示され，エラーを出さないように修正
### まだ実装できていないこと
  + 文書一覧の表示形式をJayと同じように1行に1つの文書になるようにする
  + preview タブの表示にCSSを適用する

**Comment by miyake13000** [comment]
#20 により対応されたためクローズする．
