### ISSUE TITLE
API token を発行できるようにする

### ISSUE THREAD

**Issue by masafumi0612** [nomlab/rask#12]
Created from [AI0802](http://jay.swlab.cs.okayama-u.ac.jp/minutes/1190?ai=0802) of minute 1190.
+ API token を発行できるようにする -->(野村 !:0802)

**Comment by masafumi0612** [comment]
ApiToken テーブルを作成する(以下，カラム)．
・secret (APIトークン)
・description (トークン名)
・expired_at (有効期限)
・user_id (外部キー)

**Comment by masafumi0612** [comment]
#9 で PR を作成

**Comment by masafumi0612** [comment]
API トークン一覧に作成者を記載する．
各トークンの右にある詳細のリンクを削除する．
ユーザ詳細ページでAPI トークンの一覧が見られるようにする．

**Comment by masafumi0612** [comment]
#9 で 対応

**Comment by miyake13000** [comment]
#9 により対応されたたためクローズする．
